### ISSUE TITLE
Broker: Unknown member

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications-email#33]
### Description of the bug

Look into the `KafkaException` with message `Broker: Unknown member` and try to fix it.

It could be that we're using the wrong [consumer group id](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1464).

### Steps To Reproduce

The error happens when a consumer tries to commit. It happens in ConsumeMessage() in KafkaConsumerBase.

### Threat modeling
This is a bug fix and not a change.

**Comment by acn-sbuad** [comment]
Last entry of broker unknown member was on 11/10/2023, 9:32:00.830 AM.  Before consumer group id was altered and before rate limits in Communication services were raised. Health checks we're disabled a while before this date as well (nov 3rd)
Closing issue for now. We can reopen if error occurs again.
